---
author: "Fernando Moreno Jabato"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    fig_width: 12
---

<style type='text/css'>
    body .main-container {
        max-width: 90%;
    }

    .plot_real_size {
    	overflow: scroll;
  	}

    .plot_real_size img{
    	max-width: none;
    	max-height: none;
    }

    embed {
   		width: 800px;
  		height: 800px;
  }   
</style>

```{r config, include = FALSE}
 
# Load necessary packages
require(ggplot2)
require(knitr)

```

# **Cluster `r cl` - Correlation profiles report** 

## **Profiles data**
Statistics about input results obtained from DEGenes Expression Hunter are:
```{r table_exp_flags, echo = FALSE}
cl_table <- as.data.frame(table(DEGH_results$genes_tag[which(DEGH_results$Cluster_ID == cl)]))
names(cl_table) <- c("Gene_tag","Genes")
knitr::kable(cl_table)
```

```{r load_correlation_stats, echo = FALSE}
curr_out <- knit_expand("partial/corr_cl_stats.Rmd")
```

`r paste(knit(text = curr_out), collapse = '\n')`

