---
author: "SysBioLab"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    fig_width: 12
---

<style type='text/css'>
    body .main-container { 
        max-width: 90%;
    
    }

    .plot_real_size {
      overflow: scroll;
      max-height: 600px;
    }

    .plot_real_size img{
      max-width: none;
      max-height: none;
    }

    embed {
   
  }   
</style>

# **Functional Report**


```{r main_init, echo = FALSE, warning =FALSE, message=FALSE, results = 'asis'} 
gene_set <- cluster
if (!is.null(opt$description)){
	cat(opt$description)
}

```


```{r render_partial, echo = FALSE, warning =FALSE, message=FALSE, results = 'asis'} 

expanded_report <- ""
# Per each category defined, perform enrichment

for (funsys in names(enrichments_for_reports[[gene_set]])){
	if (funsys %in% c("BP", "CC", "MF"))
		funsys_txt <- paste0("Gene Onthology ", funsys)
    funsysTitleText <- paste0("## **",funsys_txt," enrichment results**\n") # Header
    expanded_report <- c(expanded_report, funsysTitleText, knitr::knit_expand("partial/ora_enrichResult_new.Rmd")) # Body
}  

```

`r paste(knitr::knit(text = expanded_report), collapse = '\n')`
