---  
title: "ExpHunterSuite: Functional Report"
author: "SysBioLab"
output: 
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    fig_width: 12
---

<style type='text/css'>
    body .main-container {
        max-width: 90%;

    }

    .plot_real_size {
      overflow: scroll;
      max-height: 600px;
    }

    .plot_real_size img{
      max-width: none;
      max-height: none;
    }

    embed {
   
  }   
</style>

```{r config, include=FALSE, message=FALSE}
require(ggplot2)
require(knitr)
require(clusterProfiler)
require(enrichplot)
require(DOSE)
```

```{r child="func_initial_details.Rmd"}
```
```{r child="func_top_genes.Rmd"}
```

```{r ORA_analysis, echo=FALSE, results='asis', message=FALSE, warning=FALSE}
# Load necessary packages

# JRP - to reuse Jose's bits
gene_set <- "ORA"
res_ora <- list()
for(funsys in names(flags_ora)) {

# print(funsys)
#res <- lapply(func_results_new$ORA, function(x) {
#  print(typeof(x))
  if(flags_ora[[funsys]] == TRUE) {
    enrich_obj <- func_results$ORA[[funsys]]
   #   res[[funsys]] <- knitr::knit_child(
   #     "ora_plots_all_objects.Rmd", envir = environment(), quiet = TRUE
   # )
    exp_res <- knitr::knit_expand("ora_plots_all_objects.Rmd")
    res_ora[[funsys]] <- knitr::knit(text=exp_res, quiet=TRUE)
  } else {
    res_ora[[funsys]] <- paste0("## **No enrichment found for", funsys, "**\n")
  }
}
cat(unlist(res_ora), sep = '\n')

# res_gsea <- list()
# for(funsys in names(flags_gsea)) {
#     cat(paste0("## **flags_gsea", funsys, "**\n"))


# #res <- lapply(func_results_new$ORA, function(x) {
# #  print(typeof(x))
#   if(flags_gsea[[funsys]] == TRUE) {
#     enrich_obj <- func_results$GSEA[[funsys]]
#     print(enrich_obj)
#    #   res[[funsys]] <- knitr::knit_child(
#    #     "ora_plots_all_objects.Rmd", envir = environment(), quiet = TRUE
#    # )
# cat("testing here")
#     exp_res <- knitr::knit_expand("gsea_plots_all_objects.Rmd")
#     res_gsea[[funsys]] <- knitr::knit(text=exp_res)
#   } else {
#     cat(paste0("## **No enrichment found for", funsys, "**\n"))
#   }
# }
# cat(unlist(res_gsea), sep = '\n')

```

## **Values of options used to run Functional Hunter**
First column contains the option names; second column contains the given values for each option in this run.
```{r opt_vals, echo = FALSE}
#knitr::kable(cbind(func_results$final_main_params))
```